title: Faces of Books
description: Typography Blog
footer_text: Copyright 2021 Max Kielesinska
header_feature_image: ../uploads/pages.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items: []
