title: Faces of Books
description: Typography Blog
footer_text: Copyright 2021 Max Kielesinska
header_feature_image: ../uploads/34ef9989-0488-4057-8c19-baef3726fc96.jpeg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo2.jpg
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme/
    tab: true
