title: Your name or name of site
description: A website with a blog
footer_text: Copyright 2021 Your name
header_feature_image: ../uploads/pages.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 35px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
